### ISSUE TITLE
iPad not considered mobile

### ISSUE THREAD

**Issue by stuckinaboot** [juliangruber/is-mobile#25]
First of all, great job with this npm module- I love it!

I noticed one issue, however, when viewing my website on my iPad where my website was treating my iPad as a desktop device rather than a mobile device. I am using is-mobile to determine mobile/not mobile.

I managed to reproduce the bug using `detectmobilebrowsers.com` by doing the following:
1. Open chrome on desktop and navigate to detectmobilebrowsers.com
2. Right-click anywhere on the page and press inspect. The console and some dev tools should show
3. At the top of the page, there should be a chrome dev tool dropdown that is labelled "Responsive". Click on this and choose iPad.
4. Refresh the page. The iPad user agent will be shown but detectmobilebrowsers will say "No mobile browser detected." The iPad user agent shown is `Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1`.

My code for detecting mobile environments looks like the following:
```
import isMobileBrowser from "is-mobile";
const mobile = isMobileBrowser({ tablet: true, featureDetect: true });
// mobile is incorrectly false for iPads
```

Am I doing something wrong or is this a bug?

**Comment by joemillervi** [comment]
Should technically be a bug. I guess what i want is isPhone :b

**Comment by ptrxyz** [comment]
Any plans on fixing this? It seems to be still present.

**Comment by juliangruber** [comment]
I think we fixed the original issue, since the tablet regular expression is now this:

https://github.com/juliangruber/is-mobile/blob/1fa47ecba908551b9f606ff1a813e616a4aea6e5/index.js#L9

For iPad with Safari I think you need to enable `featureDetect`, @ptrxyz can you try this?

**Comment by juliangruber** [comment]
> For iPad with Safari I think you need to enable `featureDetect`, @ptrxyz can you try this?

See https://github.com/juliangruber/is-mobile/issues/17 and https://github.com/juliangruber/is-mobile/pull/22

**Comment by ptrxyz** [comment]
Sadly I am no longer in possession of the iPad (borrowed one for testing purposes) and thus I can't ... :/

**Comment by csmartinsfct** [comment]
@juliangruber can confirm that enabling `featureDetect` works for me on the iPad with Safari.

**Comment by juliangruber** [comment]
Thank you for confirming!

Closing since it works with the `featureDetect` option.
