### ISSUE TITLE
Consider tablets? iPad etc.

### ISSUE THREAD

**Issue by dy** [juliangruber/is-mobile#3]
Hi @juliangruber!

Your package is being used at plotly.js, but there seems  to be a trouble detecting tablets, in particular https://github.com/plotly/plotly.js/issues/280. Should this package consider tablet a mobile, or it is better to come up with a separate package `is-tablet`? Thank you!

**Comment by juliangruber** [comment]
This is a very interesting issue! Eventually I think there any distinguishing laptop / tablet / mobile will be useless, but for now, what about extending this api to be

```js
isMobile() => isPhone() || isTablet()
isPhone()
isTablet()
```

**Comment by vkehayas** [comment]
Another user simply [suggested](https://github.com/plotly/plotly.js/pull/1411#issuecomment-360503918) replacing

`ip(hone|od)`
with
`ip(ad|hone|od)`

to add support for the ipad.

**Comment by juliangruber** [comment]
Does anyone want to take the lead on this?
