### ISSUE TITLE
ES5 friendly v3

### ISSUE THREAD

**Issue by archmoj** [juliangruber/is-mobile#31]
https://github.com/juliangruber/is-mobile/compare/v2.2.2...v3.0.0

shows ES6 syntax in `index.js`

Could you possibly use `var` instead of `const` and `let` there so that the v3 module could simply be required in ES5 please?

**Comment by juliangruber** [comment]
We made v3 a breaking change for that reason, if you want to use it in older environments then transpiring is your best bet, or simply sticking with v2

**Comment by juliangruber** [comment]
Nowadays the vast majority of platforms support ES6, and sticking to ES5 would inhibit progress.
