### ISSUE TITLE
Samsung tablet not be considered as mobile

### ISSUE THREAD

**Issue by FujiBilly** [juliangruber/is-mobile#33]
First of all, great job with this npm module~

And I noticed one issue, it's return false when the user-agent is `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/16.0 Chrome/92.0.4515.166 Safari/537.36`.

I run the sample with node.js:
```
const isMobile = require('is-mobile');
const result = isMobile({ ua: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/16.0 Chrome/92.0.4515.166 Safari/537.36', tablet: true });
console.log(result); // false
```

Hoping to help, thanks!!!

**Comment by juliangruber** [comment]
Thank you for reporting!

https://github.com/juliangruber/is-mobile/releases/tag/v3.1.0
