### ISSUE TITLE
armv7l detection catches chromebooks which should not be marked as mobile

### ISSUE THREAD

**Issue by dbasilio** [juliangruber/is-mobile#34]
We recently updated to v3.1 of the library (we were on 0.3 before). We pretty quickly had user reports come in that they were getting mobile views on chromebooks. We traced down their user agents which look like this: 
`Mozilla/5.0 (X11; CrOS armv7l 12105.100.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.144 Safari/537.36`

For reference, these are a few more user agents on chromebooks from our logs:
`Mozilla/5.0 (X11; CrOS aarch64 14388.61.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.107 Safari/537.36`
`Mozilla/5.0 (X11; CrOS x86_64 14092.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.107 Safari/537.36`

We're putting in some logic to look for the `CrOS` string and identify it as a desktop device. The library should potentially be updated to do the same.

**Comment by juliangruber** [comment]
The first user agent is detected as mobile because it contains `armv7l`.

The second and third one aren't detected as mobile, according to our regular expression.

I first thought that excluding `CrOS` is an option, but I think that's only going to work for the mobile check, not the tablet one. Probably that's good enough for you though?

**Comment by dbasilio** [comment]
I'm not sure how you would separate out tablet users :\ For our purposes we want to treat them as desktop users, but from the user agent strings I looked through I didn't find a way to separate out tablet users :\

**Comment by juliangruber** [comment]
Ok, let's just improve the mobile check for now then

**Comment by dbasilio** [comment]
Thanks for responding so quickly to this 🙏
