### ISSUE TITLE
SamsungBrowser always considered mobile

### ISSUE THREAD

**Issue by haakonmt** [juliangruber/is-mobile#35]
It seems like SamsungBrowser user agents are always considered mobile, but that isn't always the case.

Examples that are not phones, but return `true` when `tablet` is `false`:
- `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/16.0 Chrome/92.0.4515.166 Safari/537.36`
- `Mozilla/5.0 (Linux; Android 7.0; SAMSUNG SM-T815 Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/6.2 Chrome/56.0.2924.87 Safari/537.36`

**Comment by juliangruber** [comment]
For these two examples, do you know which is the string that makes it not a phone?

**Comment by haakonmt** [comment]
I believe that they would contain the word `Mobile` if they were: https://developer.samsung.com/internet/user-agent-string-format.html

**Comment by juliangruber** [comment]
Fix in https://github.com/juliangruber/is-mobile/pull/36
